server:
  port: 9090
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
ed-module-app:
  messages:
    ed-rule-url: https://ashokit-ed-rules-api.herokuapp.com/rules
